# Final Project
# UI file for interacting with the user and displaying data.

library(shiny)

# Start up the shinyUI, making a fluid page
shinyUI(
  fluidPage(
    sidebarPanel(
      textInput(inputId = 'youtube',
                label = "Youtube link",
                value = "www.youtube.com/embed/bbPaI_OQBUA"
                ),
      
      textInput(inputId = 'title',
                   label = "Title of Song"
                   ),
      
      textInput(inputId = 'artist',
                label = "Artist"
                ),
      
      submitButton(text = "Search")
    ),
    
    # Main panel to display the plot generated by the server
    mainPanel(
      uiOutput('youtube'), h2("Lyrics"),
      uiOutput('lyrics')
    )
  )
)
