# Final Project
# UI file for interacting with the user and displaying data.

library(shiny)
library(shinythemes)

# Start up the shinyUI, making a fluid page
shinyUI(
  fluidPage(theme = shinytheme("superhero"), ## Easy bootstrap theme changing.
    
    # add a header to the page; additionally, gives a title for the browser
    #  to use
    headerPanel(title = "Quick song info", windowTitle = "Quick song info"),
    
    # Left panel with query controls - notably, won't submit until the button
    # is pressed or enter is.
    sidebarPanel(
      textInput(inputId = 'title',
                   label = "Title of Song (Required)",
                value = "Alphabet Aerobics"
                   ),
      textInput(inputId = 'artist',
                label = "Artist"
                ),
      submitButton(text = "Search"),
      width = 3
      
      ## TODO: Add a `random` box, that takes from a manually selected
      #list:
      # Alphabetic Aerobics by Blackalicious
      # Yellow by ColdPlay
      # The Sounds of Silence by Simon and Garfunkel
      # Mr Brightside by The Killers
      # Wheels on the Bus by Raffi -- missing lyrics but w/e
      # Sultans of Swing by Dire Straits
    ),
    
    # Main panel to display the youtube video and lyrics generated by the server
    mainPanel(
      uiOutput('youtube'), 
      h1("Lyrics"),
      uiOutput('lyrics'),
      width = 6
    ),
    
    # Right panel with meta data about current chosen song.
    sidebarPanel(
      uiOutput("meta"),
      width = 3,
      # link to GH
      tags$p(
        tags$a(
            href="https://github.com/iEvilMango/INFO201FinalProjectAE2",
            "Ping us on GitHub with any issues, or to dig around in the source code"
              )
            )
    )
  )
)
